/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PacienteController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gil
 */
public class AdicionaPaciente extends javax.swing.JFrame {

    /**
     * @return the campoCns
     */
    public javax.swing.JTextField getCampoCns() {
        return campoCns;
    }

    /**
     * @param campoCns the campoCns to set
     */
    public void setCampoCns(javax.swing.JTextField campoCns) {
        this.campoCns = campoCns;
    }

    /**
     * @return the campoCpf
     */
    public javax.swing.JTextField getCampoCpf() {
        return campoCpf;
    }

    /**
     * @param campoCpf the campoCpf to set
     */
    public void setCampoCpf(javax.swing.JTextField campoCpf) {
        this.campoCpf = campoCpf;
    }

    /**
     * @return the campoNome
     */
    public javax.swing.JTextField getCampoNome() {
        return campoNome;
    }

    /**
     * @param campoNome the campoNome to set
     */
    public void setCampoNome(javax.swing.JTextField campoNome) {
        this.campoNome = campoNome;
    }

    private final PacienteController controller;

    /**
     * Creates new form AdicionaPaciente
     */
    public AdicionaPaciente() {
        initComponents();
        controller = new PacienteController(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoCpf = new javax.swing.JTextField();
        campoCns = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoCepPaciente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoRuaPaciente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoNumeroPaciente = new javax.swing.JTextField();
        campoComplementoPaciente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoBairroPaciente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campoCidadePaciente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoUfPaciente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Controle de atendimento aos pacientes");

        jLabel2.setText("Cadastro de Paciente");

        jLabel3.setText("Nome");

        jLabel4.setText("CPF");

        jLabel5.setText("CNS");

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });

        campoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpfActionPerformed(evt);
            }
        });

        campoCns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCnsActionPerformed(evt);
            }
        });

        jLabel6.setText("CEP");

        campoCepPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCepPacienteActionPerformed(evt);
            }
        });

        jLabel7.setText("Rua");

        campoRuaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRuaPacienteActionPerformed(evt);
            }
        });

        jLabel8.setText("Numero");

        campoComplementoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoComplementoPacienteActionPerformed(evt);
            }
        });

        jLabel10.setText("Bairro");

        jLabel11.setText("Cidade");

        jLabel12.setText("Estado");

        jLabel13.setText("Complemento");

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoCidadePaciente)
                    .addComponent(campoBairroPaciente)
                    .addComponent(campoCpf)
                    .addComponent(campoNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoCns)
                    .addComponent(campoRuaPaciente)
                    .addComponent(campoCepPaciente)
                    .addComponent(campoNumeroPaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoComplementoPaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoUfPaciente)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCepPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoRuaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoBairroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNumeroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoComplementoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCidadePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoUfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(149, 149, 149))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCpfActionPerformed

    private void campoCnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCnsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            controller.salvar();
        } catch (SQLException ex) {
            Logger.getLogger(AdicionaPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoComplementoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoComplementoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoComplementoPacienteActionPerformed

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            controller.salvar();
            Dashboard dashboard = new Dashboard();
            dashboard.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AdicionaPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void campoCepPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCepPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCepPacienteActionPerformed

    private void campoRuaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRuaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRuaPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoBairroPaciente;
    private javax.swing.JTextField campoCepPaciente;
    private javax.swing.JTextField campoCidadePaciente;
    private javax.swing.JTextField campoCns;
    private javax.swing.JTextField campoComplementoPaciente;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumeroPaciente;
    private javax.swing.JTextField campoRuaPaciente;
    private javax.swing.JTextField campoUfPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the campoBairroPaciente
     */
    public javax.swing.JTextField getCampoBairroPaciente() {
        return campoBairroPaciente;
    }

    /**
     * @param campoBairroPaciente the campoBairroPaciente to set
     */
    public void setCampoBairroPaciente(javax.swing.JTextField campoBairroPaciente) {
        this.campoBairroPaciente = campoBairroPaciente;
    }

    /**
     * @return the campoCepPaciente
     */
    public javax.swing.JTextField getCampoCepPaciente() {
        return campoCepPaciente;
    }

    /**
     * @param campoCepPaciente the campoCepPaciente to set
     */
    public void setCampoCepPaciente(javax.swing.JTextField campoCepPaciente) {
        this.campoCepPaciente = campoCepPaciente;
    }

    /**
     * @return the campoCidadePaciente
     */
    public javax.swing.JTextField getCampoCidadePaciente() {
        return campoCidadePaciente;
    }

    /**
     * @param campoCidadePaciente the campoCidadePaciente to set
     */
    public void setCampoCidadePaciente(javax.swing.JTextField campoCidadePaciente) {
        this.campoCidadePaciente = campoCidadePaciente;
    }

    /**
     * @return the campoComplementoPaciente
     */
    public javax.swing.JTextField getCampoComplementoPaciente() {
        return campoComplementoPaciente;
    }

    /**
     * @param campoComplementoPaciente the campoComplementoPaciente to set
     */
    public void setCampoComplementoPaciente(javax.swing.JTextField campoComplementoPaciente) {
        this.campoComplementoPaciente = campoComplementoPaciente;
    }

    /**
     * @return the campoNumeroPaciente
     */
    public javax.swing.JTextField getCampoNumeroPaciente() {
        return campoNumeroPaciente;
    }

    /**
     * @param campoNumeroPaciente the campoNumeroPaciente to set
     */
    public void setCampoNumeroPaciente(javax.swing.JTextField campoNumeroPaciente) {
        this.campoNumeroPaciente = campoNumeroPaciente;
    }

    /**
     * @return the campoRuaPaciente
     */
    public javax.swing.JTextField getCampoRuaPaciente() {
        return campoRuaPaciente;
    }

    /**
     * @param campoRuaPaciente the campoRuaPaciente to set
     */
    public void setCampoRuaPaciente(javax.swing.JTextField campoRuaPaciente) {
        this.campoRuaPaciente = campoRuaPaciente;
    }

    /**
     * @return the campoUfPaciente
     */
    public javax.swing.JTextField getCampoUfPaciente() {
        return campoUfPaciente;
    }

    /**
     * @param campoUfPaciente the campoUfPaciente to set
     */
    public void setCampoUfPaciente(javax.swing.JTextField campoUfPaciente) {
        this.campoUfPaciente = campoUfPaciente;
    }
}
